site_name: Rewrite-Odoo
theme:
  name: material
  language: my

  icon:
    repo: HanZawNyein/rewrite-odoo
  repo_url: https://github.com/HanZawNyein/rewrite-odoo

  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences